export const ErrorCode = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID',
  AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Product
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_OUT_OF_STOCK: 'PRODUCT_OUT_OF_STOCK',

  // Category
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',

  // Cart
  CART_EMPTY: 'CART_EMPTY',
  CART_NOT_FOUND: 'CART_NOT_FOUND',

  // Cart Rules
  CART_RULE_INVALID: 'CART_RULE_INVALID',
  CART_RULE_EXPIRED: 'CART_RULE_EXPIRED',
  CART_RULE_NOT_FOUND: 'CART_RULE_NOT_FOUND',

  // Order
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_INVALID_STATE: 'ORDER_INVALID_STATE',

  // Payment
  PAYMENT_FAILED: 'PAYMENT_FAILED',

  // Carrier
  CARRIER_NOT_AVAILABLE: 'CARRIER_NOT_AVAILABLE',
  CARRIER_NOT_FOUND: 'CARRIER_NOT_FOUND',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Address
  ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',

  // General
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
