import { Router } from 'express';
import { authRouter } from '../modules/auth/routes.js';
import { productRouter } from '../modules/product/routes.js';
import { searchRouter } from '../modules/search/routes.js';
import { categoryRouter } from '../modules/category/routes.js';
import { cartRouter } from '../modules/cart/routes.js';
import { userRouter } from '../modules/user/routes.js';
import { addressRouter } from '../modules/address/routes.js';
import { manufacturerRouter } from '../modules/manufacturer/routes.js';
import { supplierRouter } from '../modules/supplier/routes.js';
import { attributeRouter } from '../modules/attribute/routes.js';
import { featureRouter } from '../modules/feature/routes.js';
import { taxRouter } from '../modules/tax/routes.js';
import { carrierRouter } from '../modules/carrier/routes.js';
import { geoRouter } from '../modules/geo/routes.js';
import { orderRouter } from '../modules/order/routes.js';
import { discountRouter } from '../modules/discount/routes.js';
import { paymentRouter } from '../modules/payment/routes.js';
import { configurationRouter } from '../modules/configuration/routes.js';
import { stockRouter } from '../modules/stock/routes.js';
import { mailRouter } from '../modules/mail/mail.routes.js';
import { analyticsRouter } from '../modules/analytics/routes.js';
import { wishlistRouter } from '../modules/wishlist/routes.js';
import { reviewRouter } from '../modules/review/routes.js';
import { cmsRouter } from '../modules/cms/routes.js';
import { returnRouter } from '../modules/return/routes.js';
import { customerGroupRouter } from '../modules/customer-group/routes.js';
import { langRouter } from '../modules/lang/routes.js';
import { loyaltyRouter } from '../modules/loyalty/routes.js';
import { translationRouter } from '../modules/translation/routes.js';
import { affiliateRouter } from '../modules/affiliate/routes.js';
import { newsletterRouter } from '../modules/newsletter/routes.js';
import { invoiceController } from '../modules/invoice/invoice.controller.js';
import { themeRouter } from '../modules/theme/theme.routes.js';
import { emailTemplatesRouter } from '../modules/mail/email-templates.routes.js';
import { currencyRouter } from '../modules/currency/routes.js';
import { supportRouter } from '../modules/support/routes.js';
import { authenticate } from '../middleware/authenticate.js';
import { asyncHandler } from '../middleware/async-handler.js';

export const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/products', productRouter);
apiRouter.use('/categories', categoryRouter);
apiRouter.use('/cart', cartRouter);
apiRouter.use('/users', userRouter);
apiRouter.use('/addresses', addressRouter);
apiRouter.use('/manufacturers', manufacturerRouter);
apiRouter.use('/suppliers', supplierRouter);
apiRouter.use('/attributes', attributeRouter);
apiRouter.use('/features', featureRouter);
apiRouter.use('/tax', taxRouter);
apiRouter.use('/carriers', carrierRouter);
apiRouter.use('/geo', geoRouter);
apiRouter.use('/orders', orderRouter);
apiRouter.use('/discounts', discountRouter);
apiRouter.use('/payment', paymentRouter);
apiRouter.use('/configurations', configurationRouter);
apiRouter.use('/search', searchRouter);
apiRouter.use('/stock', stockRouter);
apiRouter.use('/mail', mailRouter);
apiRouter.use('/analytics', analyticsRouter);
apiRouter.use('/wishlist', wishlistRouter);
apiRouter.use('/reviews', reviewRouter);
apiRouter.use('/cms', cmsRouter);
apiRouter.use('/returns', returnRouter);
apiRouter.use('/customer-groups', customerGroupRouter);
apiRouter.use('/langs', langRouter);
apiRouter.use('/', loyaltyRouter); // Loyalty mounts /account/loyalty, /cart/apply-loyalty, /admin/...
apiRouter.use('/theme', themeRouter);
apiRouter.use('/admin/email-templates', emailTemplatesRouter);
apiRouter.use('/translations', translationRouter);
apiRouter.use('/', affiliateRouter);
apiRouter.use('/', newsletterRouter);
apiRouter.use('/currencies', currencyRouter);
apiRouter.use('/support', supportRouter);
apiRouter.use('/admin', supportRouter);

// Invoice download: GET /api/v1/orders/:id/invoice
apiRouter.get('/orders/:id/invoice', authenticate, asyncHandler(invoiceController.downloadInvoice));

